### ISSUE TITLE
no source

### ISSUE THREAD

**Issue by TeoTwawki** [EDGECOM666/xi_server_manager#1]
you put a zip file in a repository. we're not supposed to put binary files in git repo's (because git is TERRIBLE at managing binary files), that would go in the [releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) tab _after_ source code was uploaded.

**Comment by EDGECOM666** [comment]
I think I fixed it I deleted the .exe from source on main branch. let me know if its ok now

**Comment by TeoTwawki** [comment]
source looks good, you may still want to get the binary files (exe, zip, etc) out and put them to a release upload instead though. it'll bloat your repository every time changes are made.

**Comment by EDGECOM666** [comment]
I did I am pretty sure 

https://github.com/EDGECOM666/xi_server_manager/releases/tag/XI_Server_Manager_v1.0.0

**Comment by EDGECOM666** [comment]
ohh just delete the bin folder you mean
